### ISSUE TITLE
High Priority - Changed threshold for PREFACEFF

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#100]
The PREFACEFF (FFPF) data is very unreliable until we update with more data in the model. I'd like the threshold to be lowered to only flag very low (rare) values i.e. below 4% (with red color). We will fail those as a precaution unless we have FFY data that supports sufficient ff.

**Comment by mayabrandi** [comment]
You mean you want: 

Red flagg if fetal_fraction_pf < 4 and fetal_fraction_y < 0.6.

instead of as it is now:

Red flagg if fetal_fraction_pf < 7 and fetal_fraction_y < 0.6

Correct?

**Comment by alieden** [comment]
Yes, correct i.e. the threshold for PREFACEFF can be lowered.

Från: mayabrandi ***@***.***>
Skickat: den 26 juli 2021 12:34
Till: Clinical-Genomics/statina ***@***.***>
Kopia: Agne Liedén ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/statina] High Priority - Changed threshold for PREFACEFF (#100)


You mean you want:

Red flagg if fetal_fraction_pf < 4 and fetal_fraction_y < 0.6.

instead of as it is now:

Red flagg if fetal_fraction_pf < 7 and fetal_fraction_y < 0.6

Correct?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fstatina%2Fissues%2F100%23issuecomment-886581598&data=04%7C01%7Cagne.lieden%40ki.se%7Cec739bda9e2047ce6d6408d95020de9a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637628924368295028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4I5G8bAcgaPQ2dqAfqiw%2Fi0YovLnULTkL0FVynKpam4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNPY7DBC2QKPCPNQYKA6WDTZU2ZFANCNFSM5ABFAXAQ&data=04%7C01%7Cagne.lieden%40ki.se%7Cec739bda9e2047ce6d6408d95020de9a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637628924368305024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8YHEPBDG%2FYs91l1%2BctBRHBAUBPjoyYxil4AlSWKZGYE%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.
