### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/statina#129]
When calling the endoints from statina-ui I get this error. 
`
Access to XMLHttpRequest at 'http://localhost:28003/batches' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

It's a CORS error.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

inspo to solve it:
https://stackoverflow.com/questions/22181384/javascript-no-access-control-allow-origin-header-is-present-on-the-requested

**Comment by Mropat** [comment]
Statina is written with FastAPI. [Here](https://fastapi.tiangolo.com/tutorial/cors/) is a FastAPI solution
