### ISSUE TITLE
Order of samples in the NIPT viewer (medium priority)

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#149]
Hej,

Vi laddar bara upp en json fil i orderportalen och ni gör sedan sample sheet etc. Jag kollade jsonfilen för denna order och ser inget konstigt med denna, vi kan (vad vi vet) inte påverka i vilken ordning proverna hamnar i sample sheet i orderportalen, så rimligen har det skett någon ändring i er hantering av data på vägen som leder till att data rapporteras annorlunda till statina nu? Vi får se hur det blir i kommande batcher?

Jag kan väl lägga en statina issue i github för att påminna er om att vi vill ha det som det var tidigare igen. 
Tänkte mest att det var rimligt att flagga att vi plötsligt fått data levererat i omvänd ordning (utan något förhandsbesked) om det skulle kunna indikera något problem.

Mvh,

Agne    

Från: Support (Clinical Genomics Scilifelab) <supportsystem@clinicalgenomics.se> 
Skickat: den 26 oktober 2021 13:08
Till: K Funk NIPT <nipt.karolinska@regionstockholm.se>
Kopia: Jesper Eisfeldt <jesper.eisfeldt@scilifelab.se>; K Funk NIPT <nipt.karolinska@regionstockholm.se>; Maya Brandi <maya.brandi@scilifelab.se>
Ämne: [#212894] 2117690_NIPT

-- do not edit --
NIPT Karolinska, 

A customer support staff member has replied to your support request, #212894 with the following response: 
Hej igen Agne,
Det är inget som har ändrats så det kan ha att göra med provordningen i sample sheet eller liknande. Utvecklarna ber dig lägga ett issue på GitHub för detta på Statina. Och lägg in prioritet så att dom vet hur viktigt detta är.

Hälsningar,
Emma

We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, login to your account for a complete archive of all your support requests and responses. 

https://Clinical-Scilifelab.supportsystem.com/view.php?id=44486 

NIPT Karolinska, 

A customer support staff member has replied to your support request, #212894 with the following response: 
Hej Agne,
Jag har skickat vidare frågan om provordningen i tabellen till våra utvecklare.
Hälsningar,
Emma

We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, login to your account for a complete archive of all your support requests and responses. 

https://Clinical-Scilifelab.supportsystem.com/view.php?id=44486 

Hej,

Vi noterade att ordningen för proverna är omkastade i batch summary table för denna batch av någon anledning? Vi ser hellre att det är som tidigare dvs lägsta numret högst upp i tabellen. 

Ska väl tilläggas att den positiva kontrollen faller ut som väntat dvs ingen indikation på att det skulle vara fel på resultatet från den jämförelsen.

Mvh,

Agne

**Comment by alieden** [comment]
Kan lägga till att dagens batch 2118843_NIPT också uppvisar samma problem dvs omvänd ordning på proverna i tabellen.

**Comment by elevu** [comment]
In the new Statina https://statina-83aa9.web.app/ we added sorting in the batch and samples table. Samples can now be sorted by many different values (Sample or Batch Id, Z score etc.)
![Dec-14-2021 16-14-20](https://user-images.githubusercontent.com/6919697/146040908-43087731-00ee-4405-8c78-79f748da18f2.gif)
