### ISSUE TITLE
Adjusting red flag and warning for Z-score in relation to FFY and/or FFPF (high priority)

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#176]
In samples with an FFY of 4,00% or larger we use a Z-score threshold of 4,0 for T13/18/21. If FFY=0% we apply the same threshold for samples with FFPF of 4,00% or larger. 

However if FFY is below 4,00% and not 0% we use a z-score threshold of 3,0 for T13/18/21.  If FFY=0% we apply the same threshold for samples with FFPF below 4,00%.

I thought this had been implemented in Statina but due to the result of 2021-31843-06 (in batch 2118955_NIPT) i realized this is not the case.

Please adjust the red flag and warning for Z-score in accordance with the above.

**Comment by alieden** [comment]
This is of course also connected to issue 170.

**Comment by mayabrandi** [comment]
These are the current rules:
<img width="544" alt="Skärmavbild 2022-01-28 kl  15 46 47" src="https://user-images.githubusercontent.com/1306333/151567273-41553702-f2ea-4e5d-a090-07fa794c4b26.png">


This is sort of how i interpret what you want. But i don't really get it..
```
if FFY >= 4,00%  and Z-score > 4,0:
	warn
elIf FFY==0 and  and Z-score > 4,0:
	warn
if FFY < 4,00% and FFY!= 0% and z-score> 3,0:
	warn 
```

But then this last additioanl rule that I dont understand

"If FFY=0% we apply the same threshold for samples with FFPF below 4,00%."


Can you help me understand this Agne

**Comment by mayabrandi** [comment]
@alieden Let me know when we chan have a chat about this

**Comment by alieden** [comment]
Sorry if this is unclear.

To summarize a bit again. This issue is a bit complicated, the FFY value is in most cases the best estimate of the fetal fraction if the fetus is XY (male). In ultra rare cases the FFY value will be 0 in a XY pregnancy but a value of 0 typically means that the fetus is XX (female). The FFPF value provides another estimate of the fetal fraction and can also be used in XX pregnancies. Unfortunately this estimate is rather poor but we (mainly Jesper) is working on improving this and adding another estimate based on insert sizes also.

After some additional consideration (and looking at the available data) I would like to have the following rules:

If FFY >= 4,00% warn if the 13/18/21 Z-score is >=4,00. Also a z-score of -8,00 or more negative should result in a warning.

If FFY <4,00 but not 0 warn if the Z-score is >=3,00. Also a z-score of -8,00 or more negative should result in a warning.

When FFY is 0 (i.e. we assume that the pregnancy is XX) the following rules apply:

If FFPF >= 4,00% warn if the 13/18/21 Z-score is >=4,00. Also a z-score of -8,00 or more negative should result in a warning.

If FFPF<4,00 warn if the Z-score is >=3,00. Also a z-score of -8,00 or more negative should result in a warning.

Regarding the warning for low fetal fraction it should warn if FFY< 3,00 but not if it's 0.

Also If FFPF < 4,00 we should get a warning for low fetal fraction.


Doable?

We could also construct the correlation between FFPF and the Z-scores in an independent way if that's easier. In that case we would not make any difference between cases having FFY=0 and the ones that have an FFY above 0.

Let me know if you want to discuss this further live

Agne


Från: mayabrandi ***@***.***>
Skickat: den 28 januari 2022 15:50
Till: Clinical-Genomics/statina ***@***.***>
Kopia: Agne Liedén ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/statina] Adjusting red flag and warning for Z-score in relation to FFY and/or FFPF (high priority) (Issue #176)


These are the current rules:
[Ska?rmavbild 2022-01-28 kl  15 46 47]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1306333%2F151567273-41553702-f2ea-4e5d-a090-07fa794c4b26.png&data=04%7C01%7Cagne.lieden%40ki.se%7Ccbb8922714ce4cf3e2be08d9e26d6853%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637789781791767580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fw1KL4gGb97VadKZq14moUla%2B5sT4HT%2F8mApx6egNUg%3D&reserved=0>

This is sort of how i interpret what you want. But i don't really get it..

if FFY >= 4,00%  and Z-score > 4,0:



        warn



elIf FFY==0 and  and Z-score > 4,0:



        warn



if FFY < 4,00% and FFY!= 0% and z-score> 3,0:



        warn



But then this last additioanl rule that I dont understand

"If FFY=0% we apply the same threshold for samples with FFPF below 4,00%."

Can you help me understand this Agne

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fstatina%2Fissues%2F176%23issuecomment-1024294113&data=04%7C01%7Cagne.lieden%40ki.se%7Ccbb8922714ce4cf3e2be08d9e26d6853%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637789781791767580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FpzY%2FcgKHdKjop0pvOvUpziQGMc393KypYXpLZIzM70%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNPY7CSLEVNME54PS5GQA3UYKUIDANCNFSM5I6W2SQA&data=04%7C01%7Cagne.lieden%40ki.se%7Ccbb8922714ce4cf3e2be08d9e26d6853%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637789781791767580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RjMiduo0eYAihGaTyDS9IJAaQeLqvh4sIlfh9nTv%2B1M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cagne.lieden%40ki.se%7Ccbb8922714ce4cf3e2be08d9e26d6853%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637789781791767580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fq1A04mts1te5KIPiycU3kUoPK29XCzHZ8VwLdUBUEc%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cagne.lieden%40ki.se%7Ccbb8922714ce4cf3e2be08d9e26d6853%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637789781791923822%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2WYQNLFRqKjIa%2F4ZaNA1HIQNPlg9JgXOApkzSDW6ayU%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by mayabrandi** [comment]
Thats a lot clearer! This is how it looks when implemented. Please have a look to double check.

![Skärmavbild 2022-01-31 kl  12 48 14](https://user-images.githubusercontent.com/1306333/151788666-ea16cebc-622c-4222-a17a-6b0f18588ec2.png)

**Comment by alieden** [comment]
The last part i.e. "fetal_fraction_Y< 4 and (z_score>=3 or z_scores <= -8): return warning" is correct only if it excludes the situation when FFY=0 which is not clear to me?

**Comment by mayabrandi** [comment]
Yes. That is taken care of since the FFY==0 condition is handled earlier. 👍

**Comment by mayabrandi** [comment]
Regarding ff_y and ff_pf warnings.. these are the warnings that you get now:
ff_y warning:
 
<img width="259" alt="Skärmavbild 2022-01-31 kl  13 17 59" src="https://user-images.githubusercontent.com/1306333/151792770-30fc27f6-0d62-4058-baf6-74d4cd2e6151.png">

ff_pf warning:
<img width="387" alt="Skärmavbild 2022-01-31 kl  13 20 25" src="https://user-images.githubusercontent.com/1306333/151792951-faa30034-fa5b-44bb-bb41-cb2d4cd2e69f.png">


But instead you want:

ff_y warning:

<img width="361" alt="Skärmavbild 2022-01-31 kl  13 24 57" src="https://user-images.githubusercontent.com/1306333/151793494-4a264223-14f1-49cb-8057-030b809b7463.png">

ff_pf warning:

<img width="198" alt="Skärmavbild 2022-01-31 kl  13 26 31" src="https://user-images.githubusercontent.com/1306333/151793648-18e2b238-8c96-47cc-a917-acf3bf5ca6c1.png">


Correct?

**Comment by alieden** [comment]
yes if the second last section means all values of FFY that are lower than 3,0 but doesn't include 0.

**Comment by mayabrandi** [comment]
Yes. That's what it means. So we remove the lower threshold of 0.6 for ff_y!?

**Comment by alieden** [comment]
yes

**Comment by mayabrandi** [comment]
since you no longer are using the soft lower threshold -4 for z-score, do you want to remove that line from the plots as well?

**Comment by mayabrandi** [comment]
And one more question.. 
when we set trisomy warnings we use the threshold 4 for ff_y. I guess that is not the same threshold as the one for ff_pf - even though that one is also set to 4. Or???  What could I call the new threshold for ff_y in this context? 

we could maybe talk on the phone if there is a risk for misunderstandings here. Or am I being clear?

**Comment by alieden** [comment]
The soft lower threshold of -4 can be removed. And the soft threshold of 2.5 is of course also removed (replaced by 3.0 when fetal fraction (ffy or ffpf) is below 4.0).

**Comment by alieden** [comment]
I'll send a figure to summarize this again. You can call me if it's still unclear:)

**Comment by alieden** [comment]
![image](https://user-images.githubusercontent.com/22740092/151942437-0de705e8-738f-4c6a-bb77-68ae6bd98062.png)

**Comment by mayabrandi** [comment]
You didnt understand my question. Better talk i guess

**Comment by alieden** [comment]
Had a look at the result of 2021-31843-06 (in batch 2118955_NIPT) again and this sample is now flagged with a yellow color for the Zscore in the table. However, there is no Z_score_21 flag in the warning column. Good if this could be added.
