### ISSUE TITLE
Lines in summary table - medium priority

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#185]
We would prefer if there were lines between rows and columns in the summary table

**Comment by elevu** [comment]
Lines added. If the changes don't show up, refresh the page.

**Comment by alieden** [comment]
Still no lines? Restart/refresh doesn't alter this

***@***.***

Från: Eleonora ***@***.***>
Skickat: den 24 januari 2022 15:07
Till: Clinical-Genomics/statina ***@***.***>
Kopia: Agne Liedén ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/statina] Lines in summary table - medium priority (Issue #185)


Lines added. If the changes don't show up, refresh the page.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fstatina%2Fissues%2F185%23issuecomment-1020136261&data=04%7C01%7Cagne.lieden%40ki.se%7Cb523755ee0ae4d00e17308d9df42c2ec%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637786300094005919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d8sTfNJQgGbvp%2FZ3y%2F9vSMkj%2BMMqJx%2F4tF5%2FiSIV40w%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNPY7H7UZNT72W4DIXUR7TUXVMHNANCNFSM5MO47W2A&data=04%7C01%7Cagne.lieden%40ki.se%7Cb523755ee0ae4d00e17308d9df42c2ec%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637786300094005919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OnJWHIfGloXL5fsVKwgzDx0OHpRNHPjvkEu3xB0U8NA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cagne.lieden%40ki.se%7Cb523755ee0ae4d00e17308d9df42c2ec%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637786300094005919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5pXobY9pUBLomTFWxvXcl9HibobCHwCeRiLL5oxfBYY%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cagne.lieden%40ki.se%7Cb523755ee0ae4d00e17308d9df42c2ec%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637786300094005919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yb7w4FURqo%2FVWLDunrwiUCjNIjnvlJJDszv345Lv9bg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by elevu** [comment]
![Screen Shot 2022-01-26 at 15 21 32](https://user-images.githubusercontent.com/6919697/151180225-0df0d1fd-cd12-4dd6-b76b-09ecd3b75685.png)

Not strong enough?

**Comment by alieden** [comment]
Barely visible😊



Från: Eleonora ***@***.***>
Skickat: den 26 januari 2022 15:23
Till: Clinical-Genomics/statina ***@***.***>
Kopia: Agne Liedén ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/statina] Lines in summary table - medium priority (Issue #185)


[Screen Shot 2022-01-26 at 15 21 32]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6919697%2F151180225-0df0d1fd-cd12-4dd6-b76b-09ecd3b75685.png&data=04%7C01%7Cagne.lieden%40ki.se%7Cd608c11894c842d6b56f08d9e0d74c3a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637788037571225647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hnS6hd2F%2BXleEh8OCS2T%2BB2mzj7Azc9LOHsdxBANJKc%3D&reserved=0>

Not strong enough?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fstatina%2Fissues%2F185%23issuecomment-1022243614&data=04%7C01%7Cagne.lieden%40ki.se%7Cd608c11894c842d6b56f08d9e0d74c3a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637788037571225647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bQvfPZcv%2BBD6Y%2By8VmJXyHjpYC3bpZyYmEwfQtVTyTU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNPY7E45MLUUF3A7K3STU3UX77STANCNFSM5MO47W2A&data=04%7C01%7Cagne.lieden%40ki.se%7Cd608c11894c842d6b56f08d9e0d74c3a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637788037571225647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JSNUD6UOs68Ow2gfug9kukrfWEDxYVJstYQhaWd2iKY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cagne.lieden%40ki.se%7Cd608c11894c842d6b56f08d9e0d74c3a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637788037571225647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hdkM7crk%2BjfJvvNf5d4Hqw0T3eA%2F9WsigqpiGZZg7Bk%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cagne.lieden%40ki.se%7Cd608c11894c842d6b56f08d9e0d74c3a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637788037571225647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q7fxWVbLcdYueErueoVicSJCJNS6lLX%2BqPnbboqZlQg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.
