### ISSUE TITLE
Alterations in headings - High Priority

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#187]
We suggest the following headings and order for the summary table to make the most important info visible at an appropiate zoom level.

Sample, Z_13, Z_18, Z_21, FFPF, FFX, FFY, Sex, Warning, Comment, QC Flag, Classification ( i.e. replacing Abnormality status), Segmental calls. Last changed.

It would also be good if the colums and rows fit the content better/more snuggly so that there is less empty space. For example there is a lot of empty space after the sample name.

**Comment by elevu** [comment]
Done, updated on the new UI https://statina-83aa9.web.app/
