### ISSUE TITLE
Presentation of sample names in Zscore 13/18/21 graphs - medium priorty

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#190]
The sample names of the current batch is shown in different ways in the graphs (13/18/21), presumably to show different options.

We prefer the option shown in the Zscore 18 graph with vertical sample names so that you don't have to change the zoom level during analyis. Preferably the zoom level should be kept at 100% all the time. We typically use 24 or 26 inch screens (1920x1200 or 2560x1440) if that helps.

**Comment by elevu** [comment]
We are using the same graph component for the Zscore graphs with vertical sample names
 ![Jan-24-2022 14-02-23](https://user-images.githubusercontent.com/6919697/150787663-2bb5f41f-71d9-4676-9f76-834206d887eb.gif)

Would you mind taking a screenshot of what is it that you would like to be displayed differently?

**Comment by elevu** [comment]
would you mind taking a screenshot of the whole page where you see this problem?

**Comment by alieden** [comment]
sent it to your email (eleonora.maccacaro@scilifelab.se).

**Comment by elevu** [comment]
thank you!

**Comment by alieden** [comment]
Please also remove the label "0" shown below the axis for the legacy data.

**Comment by alieden** [comment]
Please add Y-axis labels also
