### ISSUE TITLE
Report format - Medium priorty

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#191]
The included headings are sufficient for the reoprt but could be changed to match the summary table (after update). 
We would also prefer if the batch comment text is included in the report.

The resolution of the FFX vs FFY graph is rather low and the aspect ratio appears to be wrong also?

**Comment by elevu** [comment]
The headings have been changed and the batch comment added to the report. The ratio has been made the same with the graph not in the report. Unfortunately, the resolution comes with the Plotly library
