### ISSUE TITLE
fixed Y-axis in Zscore graph? - High priority 

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#195]
It appears that the Y-axis is fixed in the Zscore graphs. These are probably better to set to autoscale as there will be a lot of Zscores that are much higher than 10.

**Comment by alieden** [comment]
Are there any other graphs in statina that uses a fixed axis?

**Comment by elevu** [comment]
done, there shouldn't be any other graphs with fixed axis!
