### ISSUE TITLE
Error in search results - minoe 

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#197]
When you search for a sample you always get a result that includes the samples 2020-19411 and 2020-27401?

**Comment by elevu** [comment]
done

**Comment by elevu** [comment]
This will be fixed once the samples with duplicate Id will be removed

**Comment by mayabrandi** [comment]
ive removed the duplicated samples

**Comment by Mropat** [comment]
we also need to create unique index in the database for sample_id field so that creating duplicates wont be possible

**Comment by Mropat** [comment]
Samples deleted and index installed

However noticing a problem that if you search first for 2021 and then for empty string, the results dont update to show all samples again

**Comment by elevu** [comment]
> However noticing a problem that if you search first for 2021 and then for empty string, the results dont update to show all samples again

I cannot replicate this, lemme know if you see this again, meanwhile, I will close the issue
