### ISSUE TITLE
change name of full batch archive - low priority

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#204]
The full batch archive is now named "2201716_NIPT_segmental_calls" in the new version of Statina. We prefer the previous way i.e. "2201716_NIPT" since the archive contains other files than just the segmental calls etc

**Comment by moedarrah** [comment]
We are using the content-disposition in the frontend for the file name

![Screen Shot 2022-02-04 at 15 19 49](https://user-images.githubusercontent.com/41540288/152544698-473aa711-2dde-4e75-ad87-8927921b618c.png)
