### ISSUE TITLE
Incorrect sex called - High priority

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#207]
It appears that the latest changes concerning FFY has resulted in all samples being called XY according to the lab (I'm on holiday and can't view the statina page since you've restricted the access). The rule has to be that as soon as we have an FFY above 0 the result is XY (if not XXY or XYY). If memory serves me right the previous threshold was 0.6 for detecting Y.

**Comment by alieden** [comment]
Got access to the page and could confirm that all samples are called XY.

**Comment by mayabrandi** [comment]
Thats no good. Fixing immediately.

**Comment by mayabrandi** [comment]
done
