### ISSUE TITLE
Full batch archive should only include latest bundle

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/statina#214]
I noticed that when downloading full batch archive in statina, for example for batch  `2202862_NIPT`, it includes both bundles. I think this should be changed to only include the latest bundle.

**Comment by mayabrandi** [comment]
This is on purpose. Agne requested. They need to have aces to old reruns. But they should not exist as separate batch documents in the database.



> 18 feb. 2022 kl. 08:53 skrev Moa Hägglund ***@***.***>:
> 
> I noticed that when downloading full batch archive in statina, for example for batch  2202862_NIPT, it includes both bundles. I think this should be changed to only include the latest bundle.
> 
>

**Comment by mayabrandi** [comment]
closing issue hereby

**Comment by moahaegglund** [comment]
I will reopen this issue. I have discussed this with Agne over email and he approves that it's only the latest batch that should be included in the download.
