### ISSUE TITLE
Certain symbols not allowed in Comment-field?

### ISSUE THREAD

**Issue by NIPT-LabTech** [Clinical-Genomics/statina#215]
The plus sign was not accepted in the Comment-field. I am able to write it, but it isn't saved. Is there any particular reason for this? Otherwise, such limitations seem unnecessary.

/Camilla

(I don't seem to be able to change the labels, unfortunately.)

**Comment by Mropat** [comment]
Plus sign is not permitted to be sent via curl form data. [See this post with explanation](https://stackoverflow.com/questions/7410515/post-value-geting-plus-signs-removed)

To allow the plus sign,the data should be url encoded first. The FastAPI backend will automatically decode url encoded strings into ordinary strings. Currently it is possible to insert plus sign by writing %2B in the comment instead. Perhaps there is a flag that can be used to apply to url encodin to form data automatically. 

Will leave to @elevu and @moedarrah  to decide urgency

**Comment by elevu** [comment]
@NIPT-LabTech now you can submit samples with + and other special characters. Refresh the Statina page to get the new website version.
