### ISSUE TITLE
FFXXX-threshold value

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#233]
I noticed a minor issue for a recent sample (2022-35199) with FFX=-4.0 and FFY=0.0 (verified in fluffy file). This should lead to a XXX warning since the threshold should be -4.0. Is it possible to change the way this (and other?) thresholds are set to correct this? I assume one possiblity is of course to change the threshold to 3.999999 but this is not the most neat solution perhaps.

**Comment by Vince-janv** [comment]
This has now been fixed and the sample now correctly has a warning in the UI. I took the liberty of changing it so that any sample with a value equal to the threshold will receive a warning. Please let us know if you spot anything else you wish to change!
