### ISSUE TITLE
Hoover over Negative control samples

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/statina#26]
They need tho be able to hoover over negative samples in plots. Maybe have a button to activate the hoover so yoiu can chos not to hoover all the time.

[Felklassificerade prover.pdf](https://github.com/Clinical-Genomics/NIPTool/files/5988784/Felklassificerade.prover.pdf)

**Comment by moonso** [comment]
Could you add effort, gain and urgency @mayabrandi ? Or as many of them as you can

**Comment by henrikstranneheim** [comment]
@mayabrandi This was done in https://github.com/Clinical-Genomics/statina/pull/115 correct?

**Comment by mayabrandi** [comment]
yep
