### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/statina#43]
## Description

We should use internal variable names that not necessarily are the same as the fluffy output. Also we should reconsider what database models/collections to use.

## Suggested solution

Add a event collection where we store the actions taken by users

## This can be closed when 

- [ ] A new database structure is in place

**Comment by Mropat** [comment]
@mayabrandi  is this a problem currently?

**Comment by mayabrandi** [comment]
@moonso had Ideas about how we ould restructure the database, using a new collection for user events. I think it was a good id'e but he was the one with the vision. We should talk to him.
