### ISSUE TITLE
High priority - Sample not shown in the Fetal Fraction X/Y graph

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#79]
The sample 2021-18175 (batch 21100897) is not shown in the Fetal Fraction X/Y graph. Presumably because of the high FFX value (35,35).

**Comment by mayabrandi** [comment]
The reason was that only "included" samples was shown. The same for the z-score 13,18,21 plots. Ill fix so that all samples in the batch are shown, included or not.
