### ISSUE TITLE
High priority - Change FFY threshold

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#81]
The FFY threshold should be changed from 3.5 to 3.0.

**Comment by mayabrandi** [comment]
fetal_fraction_y_max is currently set to 4, not 3.5. Ill set it to 3.0

**Comment by mayabrandi** [comment]
Maybe you want to be able to change tresholds via the web interface? I could add that as a feature later in that case

**Comment by alieden** [comment]
I think its probably better if changes like that goes through an issue like this for documentation etc. We will most likely not do a lot of changes once we are past the first few months and have seen more data.
