### ISSUE TITLE
High priority - Add QC data

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#85]
We need to add the QC-data for AT_Dropout and Bin2BinVariance also. Same layout as for the other QC-data i.e. box plots.

**Comment by alieden** [comment]
Realized that we also need the "Library_nM" QC-data with the same layout. We've seen that low library yield can result in poor results recently so we need to check this. This update is really important (otherwise we have to import the data from fluffy to excel with all the risks associated with that etc.).

**Comment by Mropat** [comment]
@alieden This is included in all new fluffy outputs, with cq_flag "LibYield". But this will only work for all the new batches we analyze, so nothing applies retroactively, unless you want u to re-run a batch

**Comment by alieden** [comment]
I think we discussed this via email but I'll write it here also. It would make sense if data for all samples is included in the QC graphs (not just the included samples)

**Comment by alieden** [comment]
Sorry, what I mean is that we need the library yield data displayed just as the data for the AT_Dropout was added today
