### ISSUE TITLE
High Priority - Print report?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#86]
How do we get a pdf report of the results?

**Comment by mayabrandi** [comment]
Managed to fix a html download for you at least. Can you cope with that for a while?

**Comment by alieden** [comment]
I can't see how we could use this.

As discussed in emails etc recently, what we need for now is a basic report with just the batch summary table as a pdf. Preferably we would also like the Fetal Fraction X/Y graph included in the report and that only the aberrant samples are listed on the right (now the list is a cut version of trying to show all samples with overalapping colors etc). If you can't sort that out its better to just show the graph with previous data and batch data without a list of the samples (i.e. you can look in the printed report table to find the deviating sample). I hope this is clear?

**Comment by mayabrandi** [comment]
This is all news to me! I mean that you only want batch table and XY-plot! I can of course easily fix that. The pdf takes higher effort. I was planning to look into it sooner or later, but I didn't know it was urgent, since you have survived without it before :) If you sent the html file to the doctors, then they can scroll around and hide dots, etc. Don't you think they want that? Or They prefer to have a shorter list of only aberrant samples in the legend? I think I can fix that quite easily.  (If the doctor want, they can print the html...)

**Comment by alieden** [comment]
Exempel print screen från html report.
***@***.***D773FC.56924BA0]

Från: mayabrandi ***@***.***>
Skickat: den 8 juli 2021 13:07
Till: Clinical-Genomics/statina ***@***.***>
Kopia: Agne Liedén ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/statina] High Priority - Print report? (#86)


This is all news to me! I mean that you only want batch table and XY-plot! I can of course easily fix that. The pdf takes higher effort. I was planning to look into it sooner or later, but I didn't know it was urgent, since you have survived without it before :) If you sent the html file to the doctors, then they can scroll around and hide dots, etc. Don't you think they want that? Or They prefer to have a shorter list of only aberrant samples in the legend? I think I can fix that quite easily. (If the doctor want, they can print the html...)

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fstatina%2Fissues%2F86%23issuecomment-876346808&data=04%7C01%7Cagne.lieden%40ki.se%7C7d3c0852e13b4edbe19408d9420079d0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637613392085328865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0EpEGeAy57XLrLUrrIVIdiTv%2FK5IWEWiQ6rg%2BQ6tGP0%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNPY7HPK7LFXPQRHBSFR3DTWWBEJANCNFSM47P4XSEA&data=04%7C01%7Cagne.lieden%40ki.se%7C7d3c0852e13b4edbe19408d9420079d0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637613392085338866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hWPEPk3d0W8LyKzzST4JIY3PWNaVnGuy0v4SAsE7Ht0%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by mayabrandi** [comment]
I think you missed attaching the screen shot. Please send it again. We have tested to open the file in both firefox and chrome on different computes and it looks good.

I updated stage now to include only FF-XY plot in the report.

**Comment by alieden** [comment]
No its there if I check the sent email so something on your end. Nevermind. Tested the html file as an import to the batchresults in starlims and I think we can live with it as a temp solution if we can clean it up etc. Get back to you soon, have to help the Hamilton guy now.

Agne

8 juli 2021 kl. 13:59 skrev mayabrandi ***@***.***>:

﻿

I think you missed attaching the screen shot. Please send it again. We have tested to open the file in both firefox and chrome on different computes and it looks good.

I updated stage now to include only FF-XY plot in the report.
