### ISSUE TITLE
High priority - FFX and FFY thresholds for calling X0, XXX, XXY and XYY

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#89]
1.When there is no Y-chromosome present (FFY=0.00), FFX=3.40 (or larger) should result in a X0 warning.
2. When there is no Y-chromosome present (FFY=0.00), FFX=-1.00 (or more negative) should result in a XXX warning.

(All FFX-values in between -1,00 and 3,40 are interpreted as normal, i.e. when there is no Y-chromosome present (FFY=0.00))

**Comment by alieden** [comment]
Adding the FFY v1 (5 SD) prediction interval (for normal XY samples) data to this issue (as discussed via email). The calling of XYY or XXY is decided by a vertical line with the same value distinguishing X0 from XX as in the previous NIPT platform.
[Kopia av Prediction_interval_normal_XY_statina_v1.xlsx](https://github.com/Clinical-Genomics/statina/files/6778582/Kopia.av.Prediction_interval_normal_XY_statina_v1.xlsx)

**Comment by mayabrandi** [comment]
done
